#!/bin/bash
###############################################################
#                Unofficial 'Bash strict mode'                #
# http://redsymbol.net/articles/unofficial-bash-strict-mode/  #
###############################################################
set -euo pipefail
IFS=$'\n\t'
###############################################################


echo "Note, Use of 'pt-diagnostics' is now deprecated. Please use 'pi-top support health_check' instead."
echo "For more information, please see https://github.com/pi-top/pi-top-Python-SDK-Migration-Support"

pi-top support health_check "${@}"
